[global]
ANTHROPIC_API_KEY="[PUT YOUR OPENAI API KEY HERE]"
ANTHROPIC_MODEL_NAME="claude-3-sonnet-20240229"
OPENAI_API_KEY="[PUT YOUR OPENAI API KEY HERE]"
OPENAI_MODEL_NAME="gpt-3.5-turbo"
GROQ_API_KEY="[PUT YOUR OPENAI API KEY HERE]"
GROQ_MODEL_NAME="llama3-70b-8192"
